# Generated by Django 3.2 on 2022-12-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('key1', models.CharField(max_length=128)),
                ('key2', models.CharField(max_length=128)),
                ('cur_key', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserEtc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('user_img', models.ImageField(upload_to='images/')),
                ('user_rd', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wordcloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
    ]
