# Generated by Django 3.1.3 on 2022-12-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221221_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
