# Generated by Django 3.1.3 on 2022-12-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_usermanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
