# Generated by Django 3.1.3 on 2022-12-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuer',
        ),
    ]
